package com.hirain.aiagent.rag;
import com.hirain.aiagent.rag.model.*;import com.hirain.aiagent.rag.policy.*;import com.hirain.aiagent.rag.profile.VehicleProfileProvider;import com.hirain.aiagent.rag.retrieval.*;import com.hirain.aiagent.rag.store.*;import com.hirain.aiagent.runtime.RequestCallRegistry;import com.hirain.aiagent.runtime.RequestDeadline;import java.util.*;
/** RAG 系统服务入口；只编排可信 Profile、Lease、检索与政策，完全不知道 LangChain4j ToolCall。 */
public final class VehicleKnowledgeService {
 private final KnowledgeStoreManager stores;private final VehicleProfileProvider profiles;private final QueryNormalizer normalizer;private final HybridRetrievalCoordinator retrieval;private final EvidenceSelector evidence;private final AnswerabilityPolicy answerability;private final RequestCallRegistry calls;
 public VehicleKnowledgeService(KnowledgeStoreManager s,VehicleProfileProvider p,QueryNormalizer n,HybridRetrievalCoordinator r,EvidenceSelector e,AnswerabilityPolicy a){this(s,p,n,r,e,a,null);}
 public VehicleKnowledgeService(KnowledgeStoreManager s,VehicleProfileProvider p,QueryNormalizer n,HybridRetrievalCoordinator r,EvidenceSelector e,AnswerabilityPolicy a,RequestCallRegistry calls){stores=s;profiles=p;normalizer=n;retrieval=r;evidence=e;answerability=a;this.calls=calls;}
 public RagResult search(String requestId,String query,RequestDeadline deadline){long started=System.currentTimeMillis();if(calls!=null&&calls.isCancellationRequested(requestId))return failure(query,null,RagStatus.CANCELLED,RagFailureReason.REQUEST_CANCELLED,started);if(deadline.isExpired(started))return failure(query,null,RagStatus.TIMEOUT,RagFailureReason.DEADLINE_EXCEEDED,started);QueryNormalizationResult normalized=normalizer.normalize(query);if(!normalized.valid())return failure(query,null,RagStatus.NO_EVIDENCE,"QUERY_EMPTY".equals(normalized.failureReason())?RagFailureReason.QUERY_EMPTY:RagFailureReason.QUERY_TOO_LONG,started);VehicleProfile profile=profiles.currentProfile();if(profile==null)return failure(query,normalized.normalizedQuery(),RagStatus.NO_EVIDENCE,RagFailureReason.PROFILE_INCOMPLETE,started);KnowledgeStoreSnapshot snapshot=stores.snapshot();if(snapshot.state()==KnowledgeStoreState.UNINITIALIZED||snapshot.state()==KnowledgeStoreState.INSTALLING)return failure(query,normalized.normalizedQuery(),RagStatus.NO_EVIDENCE,RagFailureReason.KNOWLEDGE_STORE_INITIALIZING,started);if(snapshot.state()!=KnowledgeStoreState.READY)return failure(query,normalized.normalizedQuery(),RagStatus.ERROR,RagFailureReason.KNOWLEDGE_STORE_UNAVAILABLE,started);try(KnowledgeStoreLease<KnowledgeStoreGateway> lease=stores.acquire()){HybridRetrievalCoordinator.Outcome outcome=retrieval.retrieve(requestId,normalized.normalizedQuery(),lease.value(),profile,deadline);if(calls!=null&&calls.isCancellationRequested(requestId))return failure(query,normalized.normalizedQuery(),RagStatus.CANCELLED,RagFailureReason.REQUEST_CANCELLED,started);if(deadline.isExpired(System.currentTimeMillis()))return failure(query,normalized.normalizedQuery(),RagStatus.TIMEOUT,RagFailureReason.DEADLINE_EXCEEDED,started);List<RetrievalEvidence> selected=evidence.select(outcome.evidence());boolean answerableResult=answerability.answerable(selected,false,false,false);RagStatus status=answerableResult?(outcome.degradedReasons().isEmpty()?RagStatus.SUCCESS:RagStatus.DEGRADED):RagStatus.NO_EVIDENCE;RagFailureReason reason=answerableResult?null:(outcome.degradedReasons().contains(RagFailureReason.EMBEDDING_UNAVAILABLE.name())?RagFailureReason.EMBEDDING_UNAVAILABLE:null);return new RagResult(1,status,answerableResult,query,normalized.normalizedQuery(),outcome.mode(),selected,outcome.degradedReasons(),reason,System.currentTimeMillis()-started,"RAG_RESULT");}catch(Exception error){return failure(query,normalized.normalizedQuery(),RagStatus.ERROR,RagFailureReason.KNOWLEDGE_STORE_UNAVAILABLE,started);}}
 private static RagResult failure(String query,String normalized,RagStatus status,RagFailureReason reason,long started){return new RagResult(1,status,false,query,normalized,null,List.of(),List.of(),reason,System.currentTimeMillis()-started,"RAG_FAILURE");}
}
