package com.hirain.aiagent.rag.policy;
import com.hirain.aiagent.intentrouter.*;import com.hirain.aiagent.toolgroup.*;import com.hirain.aiagent.vision.routing.*;import java.util.List;import org.junit.Test;import static org.junit.Assert.*;
/** 复合能力在昂贵 Tool/60 秒 Deadline 之前终止，稳定返回拆分原因码。 */
public class KnowledgeCapabilityPlannerTest {
 @Test public void rejectsVehicleAndVisionCompoundsBeforeToolPlanning(){KnowledgeCapabilityPlanner planner=new KnowledgeCapabilityPlanner();ToolGroupSelectionResult original=ToolGroupSelectionResult.chatOnly("test",IntentConfidence.LOW);KnowledgeIntentDecision vehicle=new KnowledgeIntentDecision(KnowledgeRequirement.REQUIRED,"KNOWLEDGE_USAGE_CONDITION","v1",true);ToolGroupSelectionResult first=planner.plan(vehicle,VisionIntentDecision.none("not_visual"),original);assertEquals(ToolGroupSelectionStatus.CLARIFICATION_REQUIRED,first.status());assertEquals(KnowledgeCapabilityPlanner.COMPOUND_REQUEST_REQUIRES_SPLIT,first.selectionReason());KnowledgeIntentDecision knowledge=new KnowledgeIntentDecision(KnowledgeRequirement.REQUIRED,"KNOWLEDGE_FAULT_OR_PROMPT","v1",false);VisionIntentDecision vision=new VisionIntentDecision(VisionRequirement.REQUIRED,List.of(),"front_view",false);ToolGroupSelectionResult second=planner.plan(knowledge,vision,original);assertEquals(KnowledgeCapabilityPlanner.COMPOUND_REQUEST_REQUIRES_SPLIT,second.selectionReason());}
 @Test public void requiredKnowledgeReplacesRatherThanMergesOriginalCapabilities(){ToolGroupSelectionResult result=new KnowledgeCapabilityPlanner().plan(new KnowledgeIntentDecision(KnowledgeRequirement.REQUIRED,"KNOWLEDGE_FAULT_OR_PROMPT","v1",false),VisionIntentDecision.none("none"),ToolGroupSelectionResult.chatOnly("chat",IntentConfidence.LOW));assertEquals(List.of(ToolGroupId.VEHICLE_KNOWLEDGE_GROUP),result.selectedGroupIds());assertEquals(List.of("searchVehicleKnowledge"),result.selectedToolNames());}
 @Test public void ordinaryChatStillExposesReadOnlyKnowledgeTool(){ToolGroupSelectionResult result=new KnowledgeCapabilityPlanner().plan(KnowledgeIntentDecision.none("none"),VisionIntentDecision.none("none"),ToolGroupSelectionResult.chatOnly("chat",IntentConfidence.LOW));assertEquals(ToolGroupSelectionStatus.SELECTED,result.status());assertEquals(List.of(ToolGroupId.VEHICLE_KNOWLEDGE_GROUP),result.selectedGroupIds());assertEquals(List.of("searchVehicleKnowledge"),result.selectedToolNames());}
 @Test public void selectedVehicleToolsMergeKnowledgeWithoutDuplicates(){ToolGroupRegistry registry=ToolGroupRegistry.defaultRegistry();ToolGroupSelectionResult original=ToolGroupSelectionResult.selected(registry,List.of(ToolGroupId.AC_GROUP),"ac",IntentConfidence.HIGH);KnowledgeCapabilityPlanner planner=new KnowledgeCapabilityPlanner(registry);ToolGroupSelectionResult result=planner.plan(KnowledgeIntentDecision.none("none"),VisionIntentDecision.none("none"),original);assertEquals(List.of(ToolGroupId.AC_GROUP,ToolGroupId.VEHICLE_KNOWLEDGE_GROUP),result.selectedGroupIds());assertTrue(result.selectedToolNames().contains("set_ac_status"));assertEquals(1,result.selectedToolNames().stream().filter("searchVehicleKnowledge"::equals).count());}
 @Test public void clarificationAndFailedClosedRemainClosed(){KnowledgeCapabilityPlanner planner=new KnowledgeCapabilityPlanner();ToolGroupSelectionResult clarification=planner.plan(KnowledgeIntentDecision.none("none"),VisionIntentDecision.none("none"),ToolGroupSelectionResult.clarificationRequired("ambiguous",IntentConfidence.LOW));assertEquals(ToolGroupSelectionStatus.CLARIFICATION_REQUIRED,clarification.status());assertTrue(clarification.selectedToolNames().isEmpty());ToolGroupSelectionResult failed=planner.plan(KnowledgeIntentDecision.none("none"),VisionIntentDecision.none("none"),ToolGroupSelectionResult.failedClosed("failed"));assertEquals(ToolGroupSelectionStatus.FAILED_CLOSED,failed.status());assertTrue(failed.selectedToolNames().isEmpty());}
}
