package com.hirain.aiagent.rag.policy;
import com.hirain.aiagent.intentrouter.*;import java.util.List;import org.junit.Test;import static org.junit.Assert.*;
/** 规则测试覆盖五类车辆资料，并保护纯车控、实时状态和普通领域不被错误强制检索。 */
public class RuleBasedKnowledgeNeedDetectorTest {
 private final RuleBasedKnowledgeNeedDetector detector=new RuleBasedKnowledgeNeedDetector();
 @Test public void requiresOfficialVehicleKnowledgeButNeverOptional(){assertEquals(KnowledgeRequirement.REQUIRED,detector.decide("请查用户手册中空调的使用条件",chat()).requirement());assertEquals(KnowledgeRequirement.REQUIRED,detector.decide("P0123 故障码是什么意思",chat()).requirement());assertEquals(KnowledgeRequirement.NONE,detector.decide("打开空调",vehicle()).requirement());assertNotEquals(KnowledgeRequirement.OPTIONAL,detector.decide("前方有什么",chat()).requirement());}
 @Test public void routesVehicleMaintenanceProcedureButNotGenericProcedure(){assertEquals(KnowledgeRequirement.REQUIRED,detector.decide("Model Y如何更换空调滤清器",chat()).requirement());assertEquals("KNOWLEDGE_VEHICLE_USAGE_OR_MAINTENANCE",detector.decide("Model Y如何更换空调滤清器",chat()).reasonCode());assertEquals(KnowledgeRequirement.REQUIRED,detector.decide("How to replace ModelY cabin air filter according to owner manual?",chat()).requirement());assertEquals(KnowledgeRequirement.NONE,detector.decide("如何更换头像",chat()).requirement());}
 @Test public void coversUsageTroubleshootingServiceAndWarranty(){assertRequired("哨兵模式有什么作用","KNOWLEDGE_VEHICLE_USAGE_OR_MAINTENANCE");assertRequired("触摸屏黑屏了怎么办","KNOWLEDGE_TROUBLESHOOTING");assertRequired("成都有哪些特斯拉服务中心","KNOWLEDGE_SERVICE_CENTER");assertRequired("二手车过户以后质保还有效吗","KNOWLEDGE_WARRANTY");assertRequired("辅助转向在什么条件下可用","KNOWLEDGE_USAGE_CONDITION");}
 @Test public void recognizesNaturalQuestionsWithoutFixedMaintenancePhrase(){assertRequired("手机蓝牙为什么连不上","KNOWLEDGE_TROUBLESHOOTING");assertRequired("充电口亮红灯是什么意思","KNOWLEDGE_TROUBLESHOOTING");assertRequired("空调滤芯多久更换一次","KNOWLEDGE_VEHICLE_USAGE_OR_MAINTENANCE");assertRequired("摄像头怎样校准","KNOWLEDGE_VEHICLE_USAGE_OR_MAINTENANCE");}
 @Test public void pureControlAndRealtimeStateRemainAutoOnly(){assertNone("打开空调",vehicle());assertNone("把车窗关闭",IntentResult.of(IntentTag.VEHICLE_WINDOW,IntentConfidence.HIGH,List.of(),"","TEXT","test"));assertNone("当前还剩多少电",chat());assertNone("现在车门关了吗",chat());assertNone("播放音乐",chat());}
 @Test public void knowledgeWordingIsNotMisclassifiedAsCompoundControl(){KnowledgeIntentDecision setting=detector.decide("空调怎么设置自动模式",vehicle());assertEquals(KnowledgeRequirement.REQUIRED,setting.requirement());assertFalse(setting.compoundIntentDetected());KnowledgeIntentDecision open=detector.decide("哨兵模式怎么打开",chat());assertEquals(KnowledgeRequirement.REQUIRED,open.requirement());assertFalse(open.compoundIntentDetected());}
 @Test public void identifiesKnowledgeVehicleCompound(){assertFalse(detector.decide("空调使用条件是什么",vehicle()).compoundIntentDetected());KnowledgeIntentDecision decision=detector.decide("查一下空调使用条件，然后打开空调",vehicle());assertEquals(KnowledgeRequirement.REQUIRED,decision.requirement());assertTrue(decision.compoundIntentDetected());}
 private void assertRequired(String text,String reason){KnowledgeIntentDecision decision=detector.decide(text,chat());assertEquals(text,KnowledgeRequirement.REQUIRED,decision.requirement());assertEquals(text,reason,decision.reasonCode());}
 private void assertNone(String text,IntentResult intent){assertEquals(text,KnowledgeRequirement.NONE,detector.decide(text,intent).requirement());}
 private static IntentResult chat(){return IntentResult.of(IntentTag.CHAT,IntentConfidence.LOW,List.of(),"","TEXT","test");}
 private static IntentResult vehicle(){return IntentResult.of(IntentTag.VEHICLE_AC,IntentConfidence.HIGH,List.of(),"","TEXT","test");}
}
