package com.hirain.aiagent.rag.model;
/** 对调用方稳定的 RAG 失败原因码，禁止以异常类名或堆栈替代。 */
public enum RagFailureReason { KNOWLEDGE_STORE_INITIALIZING, KNOWLEDGE_STORE_UNAVAILABLE, PROFILE_INCOMPLETE, KNOWLEDGE_SCOPE_MISMATCH, QUERY_EMPTY, QUERY_TOO_LONG, DUPLICATE_QUERY, MULTIPLE_RAG_CALLS_IN_ITERATION, EMBEDDING_UNAVAILABLE, RERANK_UNAVAILABLE, BUNDLE_INVALID, DEADLINE_EXCEEDED, REQUEST_CANCELLED }
