package com.hirain.aiagent.rag.retrieval;

import com.hirain.aiagent.rag.cloud.QueryEmbeddingClient;import com.hirain.aiagent.rag.cloud.RagCloudException;import com.hirain.aiagent.rag.cloud.RerankCandidate;import com.hirain.aiagent.rag.cloud.RerankClient;import com.hirain.aiagent.rag.document.SourceLocatorEntityMapper;import com.hirain.aiagent.rag.model.*;import com.hirain.aiagent.rag.ranking.*;import com.hirain.aiagent.rag.store.KnowledgeStoreGateway;import com.hirain.aiagent.runtime.RequestDeadline;import java.util.*;import java.util.stream.Collectors;
/** 纯检索协调器：Lexical 始终先执行，Embedding 失败仅降级，不在此层处理 Tool 或模型 JSON。 */
public final class HybridRetrievalCoordinator {
 private final LexicalAnalyzer analyzer;private final ObjectBoxLexicalSearcher lexical;private final ObjectBoxDenseSearcher dense;private final QueryEmbeddingClient embedding;private final ReciprocalRankFusion rrf;private final RerankClient rerank;private final RerankCoordinator rerankCoordinator;private final SourceLocatorEntityMapper locator=new SourceLocatorEntityMapper();
 public HybridRetrievalCoordinator(LexicalAnalyzer a,ObjectBoxLexicalSearcher l,ObjectBoxDenseSearcher d,QueryEmbeddingClient e,ReciprocalRankFusion r){this(a,l,d,e,r,null,null);}
 public HybridRetrievalCoordinator(LexicalAnalyzer a,ObjectBoxLexicalSearcher l,ObjectBoxDenseSearcher d,QueryEmbeddingClient e,ReciprocalRankFusion r,RerankClient rerank,RerankCoordinator coordinator){analyzer=a;lexical=l;dense=d;embedding=e;rrf=r;this.rerank=rerank;rerankCoordinator=coordinator;}
 public Outcome retrieve(String requestId,String normalized,KnowledgeStoreGateway store,VehicleProfile profile,RequestDeadline deadline){List<RankedCandidate> lexicalHits=lexical.search(store,analyzer.analyze(normalized),profile,20);List<DenseCandidate> denseHits=List.of();List<String> degraded=new ArrayList<>();RetrievalMode mode=RetrievalMode.HYBRID_FUSION_ONLY;try{denseHits=dense.search(store,embedding.embed(requestId,normalized,deadline),profile,20);}catch(RagCloudException error){if(lexicalHits.isEmpty())return new Outcome(List.of(),null,List.of(error.reasonCode()));mode=RetrievalMode.LEXICAL_ONLY;degraded.add(error.reasonCode());}
 List<String> lexicalIds=lexicalHits.stream().map(RankedCandidate::chunkId).collect(Collectors.toList());List<String> denseIds=denseHits.stream().map(value->value.chunk().chunkId).collect(Collectors.toList());List<FusionCandidate> fused=rrf.fuse(denseIds,lexicalIds);Map<String,RankedCandidate> lexicalById=new HashMap<>();for(RankedCandidate item:lexicalHits)lexicalById.put(item.chunkId(),item);Map<String,DenseCandidate> denseById=new HashMap<>();for(DenseCandidate item:denseHits)denseById.put(item.chunk().chunkId,item);Map<String,com.hirain.aiagent.rag.store.entity.KnowledgeChunkEntity> chunks=new HashMap<>();for(var item:store.childChunksByIds(fused.stream().map(FusionCandidate::chunkId).collect(Collectors.toList())))chunks.put(item.chunkId,item);
 // Rerank 的输入只能来自已通过 Scope/Metadata 过滤的候选，避免将无权限或不适配内容发送到云端。
 if(mode==RetrievalMode.HYBRID_FUSION_ONLY&&rerank!=null&&rerankCoordinator!=null&&!fused.isEmpty()){List<RerankCandidate> candidates=new ArrayList<>();for(FusionCandidate item:fused){var chunk=chunks.get(item.chunkId());if(chunk!=null)candidates.add(new RerankCandidate(chunk.headingPath,chunk.content));}if(candidates.size()==fused.size())try{fused=rerankCoordinator.apply(fused,rerank.rerank(requestId,normalized,List.copyOf(candidates),deadline));mode=RetrievalMode.HYBRID_RERANKED;}catch(RagCloudException error){degraded.add(error.reasonCode());}}
 List<RetrievalEvidence> evidence=new ArrayList<>();for(int rank=0;rank<fused.size();rank++){FusionCandidate f=fused.get(rank);var c=chunks.get(f.chunkId());if(c==null)continue;DenseCandidate d=denseById.get(f.chunkId());RankedCandidate l=lexicalById.get(f.chunkId());evidence.add(new RetrievalEvidence("internal-"+c.chunkId,c.chunkId,c.parentChunkId,c.content,c.documentId,c.documentTitle,c.documentVersion,c.chapter,c.section,locator.fromChunk(c),d==null?null:d.distance(),f.denseRank(),l==null?null:l.score(),f.lexicalRank(),f.fusionScore(),rank+1,null,null,f.sources(),Applicability.EXACT));}return new Outcome(List.copyOf(evidence),mode,List.copyOf(degraded));}
 public record Outcome(List<RetrievalEvidence> evidence,RetrievalMode mode,List<String> degradedReasons){}
}
