package com.hirain.aiagent.rag;
import com.hirain.aiagent.rag.cloud.*;import com.hirain.aiagent.rag.config.RagRetrievalConfig;import com.hirain.aiagent.rag.model.*;import com.hirain.aiagent.rag.policy.*;import com.hirain.aiagent.rag.profile.VehicleProfileProvider;import com.hirain.aiagent.rag.ranking.*;import com.hirain.aiagent.rag.retrieval.*;import com.hirain.aiagent.rag.store.*;import com.hirain.aiagent.rag.store.entity.*;import com.hirain.aiagent.runtime.RequestCallRegistry;import com.hirain.aiagent.runtime.RequestDeadline;import java.util.*;import org.junit.Test;import static org.junit.Assert.*;
/** 服务级测试覆盖 Hybrid 路径、失败降级和取消短路，云端均为本地桩实现。 */
public class VehicleKnowledgeServiceTest {
 @Test public void returnsHybridEvidenceAndLexicalOnlyFallback() {VehicleKnowledgeService hybrid=service((id,q,d)->vector());RagResult first=hybrid.search("r","制动液",new RequestDeadline(System.currentTimeMillis(),5_000));assertTrue(first.answerable());assertEquals(RetrievalMode.HYBRID_FUSION_ONLY,first.retrievalMode());VehicleKnowledgeService fallback=service((id,q,d)->{throw new RagCloudException("EMBEDDING_UNAVAILABLE");});RagResult second=fallback.search("r","制动液",new RequestDeadline(System.currentTimeMillis(),5_000));assertTrue(second.answerable());assertEquals(RetrievalMode.LEXICAL_ONLY,second.retrievalMode());assertEquals(RagStatus.DEGRADED,second.status());}
 @Test public void validRerankChangesModeAndFailureFallsBackToFusion() {VehicleKnowledgeService reranked=service((id,q,d)->vector(),(id,q,c,d)->List.of(new RerankItem(0,0.9)));RagResult success=reranked.search("r","制动液",new RequestDeadline(System.currentTimeMillis(),5_000));assertEquals(RetrievalMode.HYBRID_RERANKED,success.retrievalMode());VehicleKnowledgeService fallback=service((id,q,d)->vector(),(id,q,c,d)->{throw new RagCloudException("RERANK_UNAVAILABLE");});RagResult degraded=fallback.search("r","制动液",new RequestDeadline(System.currentTimeMillis(),5_000));assertEquals(RetrievalMode.HYBRID_FUSION_ONLY,degraded.retrievalMode());assertEquals(RagStatus.DEGRADED,degraded.status());assertTrue(degraded.degradedReasons().contains("RERANK_UNAVAILABLE"));}
 @Test public void preCancelledRequestNeverStartsRetrieval() {RequestCallRegistry calls=new RequestCallRegistry();calls.cancel("cancelled");VehicleKnowledgeService service=service((id,q,d)->vector(),null,calls);RagResult result=service.search("cancelled","制动液",new RequestDeadline(System.currentTimeMillis(),5_000));assertEquals(RagStatus.CANCELLED,result.status());assertEquals(RagFailureReason.REQUEST_CANCELLED,result.failureReasonCode());}
 private static VehicleKnowledgeService service(QueryEmbeddingClient embedding){return service(embedding,null,null);}
 private static VehicleKnowledgeService service(QueryEmbeddingClient embedding,RerankClient rerank){return service(embedding,rerank,null);}
 private static VehicleKnowledgeService service(QueryEmbeddingClient embedding,RerankClient rerank,RequestCallRegistry calls){KnowledgeStoreManager stores=new KnowledgeStoreManager();stores.activate(new Gateway(),"1","m1-2026-cn-1-0-base");VehicleProfileProvider profiles=new VehicleProfileProvider(){public VehicleProfile currentProfile(){return new VehicleProfile("M1","2026","CN","1.0","BASE",0);}public boolean isDemoProfile(){return true;}};RagRetrievalConfig config=RagRetrievalConfig.v1();HybridRetrievalCoordinator retrieval=new HybridRetrievalCoordinator(new CjkLatinLexicalAnalyzer(),new ObjectBoxLexicalSearcher(new MetadataEligibilityPolicy(),config),new ObjectBoxDenseSearcher(new MetadataEligibilityPolicy()),embedding,new ReciprocalRankFusion(60),rerank,rerank==null?null:new RerankCoordinator());return new VehicleKnowledgeService(stores,profiles,new QueryNormalizer(config),retrieval,new EvidenceSelector(new EvidenceDeduplicator(),new EvidenceBudgetPolicy(100)),new AnswerabilityPolicy(),calls);}
 static final class Gateway implements KnowledgeStoreGateway {final KnowledgeStoreMetadataEntity metadata=new KnowledgeStoreMetadataEntity();final KnowledgeChunkEntity chunk=new KnowledgeChunkEntity();final LexicalTermEntity term=new LexicalTermEntity();Gateway(){metadata.knowledgeScopeId="m1-2026-cn-1-0-base";metadata.childChunkCount=1;metadata.averageLexicalDocumentLength=1;chunk.id=1;chunk.chunkId="c";chunk.parentChunkId="p";chunk.chunkLevel="CHILD";chunk.content="检查制动液";chunk.documentId="d";chunk.documentTitle="手册";chunk.documentVersion="1";chunk.sourceFormat="PDF";chunk.pdfPageStart=1;chunk.pdfPageEnd=1;chunk.headingPath="1:H";chunk.vehicleModel="M1";chunk.modelYear="2026";chunk.region="CN";chunk.softwareVersion="1.0";chunk.configurationCode="BASE";chunk.lexicalDocumentLength=1;chunk.embedding=vector();term.term="制动液";term.documentFrequency=1;term.chunkEntityIds=new long[]{1};term.termFrequencies=new int[]{1};}public KnowledgeStoreMetadataEntity metadata(){return metadata;}public List<KnowledgeChunkEntity> childChunksByIds(List<String> ids){return ids.contains("c")?List.of(chunk):List.of();}public List<KnowledgeChunkEntity> childChunksByEntityIds(List<Long> ids){return ids.contains(1L)?List.of(chunk):List.of();}public List<KnowledgeChunkEntity> nearestChildren(float[] v,int l){return List.of(chunk);}public List<LexicalTermEntity> lexicalTermsByTerms(List<String> terms){return terms.contains("制动液")?List.of(term):List.of();}public void close(){}}
 static float[] vector(){float[] value=new float[1024];Arrays.fill(value,0.1f);return value;}
}
